apiVersion: apps/v1
kind: Deployment
metadata:
  name: items
  namespace: restauranty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: items
  template:
    metadata:
      labels:
        app: items
    spec:
      containers:
        - name: items
          image: cesarboada/restauranty:items
          ports:
            - containerPort: 3003
          env:
            - name: PORT
              value: "3003"
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SECRET
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGODB_URI
            - name: CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: CLOUD_NAME
            - name: CLOUD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: CLOUD_API_KEY
            - name: CLOUD_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: CLOUD_API_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: items-service
  namespace: restauranty
spec:
  selector:
    app: items
  ports:
    - port: 3003
      targetPort: 3003