apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: restauranty
type: Opaque
stringData:
  SECRET: "MySecret1!"
  MONGODB_URI: "mongodb://mongo-service:27017/resturanty"
  CLOUD_NAME: "CHANGE_ME"
  CLOUD_API_KEY: "CHANGE_ME"
  CLOUD_API_SECRET: "CHANGE_ME"